### ISSUE TITLE
I get "Apache functions not found" even though I am on Apache

### ISSUE THREAD

**Issue by perjonsson** [melt/melt#12]
The bootstrapper thinks I am using PHP+CGI although I am using Apache/2.2.17 (Unix) mod_ssl/2.2.17 OpenSSL/1.0.0d DAV/2 PHP/5.3.6 according to PHP info.

**Comment by hnsl** [comment]
This will be fixed in the next tag.

**Comment by perjonsson** [comment]
Seems closing did not work. Is this fixed ?

**Comment by hnsl** [comment]
Per: ...are you testing with the commit above? It has not been tagged yet so you need to download HEAD.
