### ISSUE TITLE
Sample-app-default repository not found

### ISSUE THREAD

**Issue by daniel-marklund** [melt/melt#13]
In the console i want to deploy the sample-app-default but I get the following error.

melt>ghd deploy-sample-app melt/sample-app-default
This will overwrite any existing application data.
Really continue? [N/y]:y
Error: Specified repository not found (or not tagged).

**Comment by hnsl** [comment]
We  have already determined that deployment doesn't work on your machine due to 1 second HTTP timeout in php http:// configuration. This will be debugged more thoroughly when we get time to.

**Comment by perjonsson** [comment]
I can not report having this problem.
