### ISSUE TITLE
Suggested addition to core\CountryType

### ISSUE THREAD

**Issue by perjonsson** [melt/melt#14]
**Problem**
Many services such as Facebook store countries in textual format (Sweden, USA etc). The use case is to receive such information from an external service using the API and then saving that information as a CountryType in a Melt app.

**Suggested Solution**
The suggestion is to add a static function to core\CountryType that takes a textual string as input and sends the corresponding Alpha2 code as output. See below.

```
public static function getAlpha2FromName($country_name){
    $countries = core\CountryType::getCountryList();
    foreach($countries as $key => $value){
        if( $value[2] == trim( $country_name ) )
            return $key;
    }
    return null;
}
```

**Comment by hnsl** [comment]
This is impossible to implement. You can express country names with different spellings, languages, abbreviations, punctuation etc etc. I will however implement it so you can call setCountryName() with the country you got from getCountryName(). This will make it possible to input "United states" for example but you cannot input USA. The function will return false if it did not understand the country name you inputed.
