### ISSUE TITLE
Installation Create Table - Error: Specified repository not found (or not tagged).

### ISSUE THREAD

**Issue by azzuwan** [melt/melt#17]
I have created the database before I run Melt installation. This is my web console errors.
I'm on 32 bit Windows 7 machine.

melt>install
Welcome to the melt (re)installation script. Melt needs a working MySQL 5.1+ database to function. Remember that you can use your normal copy/paste hotkeys.
Do you wish to configure your MySQL details? [Y/n]y
Database host [127.0.0.1]:
Database port [3306]:
Database username [root]:
Database password []:reddoor74
Database name [melt]:
Database prefix []:
Do you have trigger permissions? [Y/n]:y
Do you have InnoDB? [Y/n]:
Configuring your installation, please wait.
melt>config db host 127.0.0.1
melt>config db port 3306
melt>config db user root
melt>config db password 
melt>config db name melt
melt>config db prefix ""
melt>config db use_trigger_sequencing true
melt>config db storage_engine innodb
Do you wish to configure your SMTP details? (Skip if your application won't send mail.) [Y/n]n
Do you wish to deploy the default sample application? (Skip if you already have an application installed.) [Y/n]y
melt>ghd deploy-sample-app melt/sample-app-default
This will overwrite any existing application data.
Really continue? [N/y]:y
Error: Specified repository not found (or not tagged).
Do you wish to syncronize the database with the application now? [Y/n]y
melt>db sync
DROP TABLE `core__metadata`

CREATE TABLE `core__metadata` (`k` varchar(16) NOT NULL PRIMARY KEY, `v` BLOB NOT NULL)

SHOW TABLES

<br />
<b>Fatal error</b>:  Class melt\cache\BlobModel contains 7 abstract methods and must therefore be declared abstract or implement the remaining methods (melt\Model::initialize, melt\Model::beforeStore, melt\Model::afterStore, ...) in <b>C:\xampp\htdocs\melt\models\cache\blob_model.php</b> on line <b>7</b><br />
Installation script complete.

**Comment by azzuwan** [comment]
Only the core_metadata table gets created. Then the script exited

**Comment by azzuwan** [comment]
Sorry I accidently clicked the close button. LOL

**Comment by hnsl** [comment]
Thanks for reporting this issue. This commit should fix this:

https://github.com/melt/melt/commit/4583678806587ceefa48e1782e30c12c49a98b3e

Feel free to close the issue if the fix works for you. :)

**Comment by azzuwan** [comment]
Hi that commit fix the db sync issues , The only thing left to solve is the failure to install sample app due to repository not found / untagged. This solves my main issue which is the db sync so I'm closing this. Thanks Hannes. Melt is great!
