### ISSUE TITLE
console url

### ISSUE THREAD

**Issue by antonellomangone** [melt/melt#18]
When i try to execute the following url:

http://localhost/melt/core/console

it gives me the following error:

Not Found

The requested URL /melt/core/console was not found on this server.
Apache/2.2.17 (Ubuntu) Server at localhost Port 80

Melt version 1.3
Ubuntu version 32bit
Linux antonello-Vostro1510 2.6.38-11-generic-pae #48-Ubuntu SMP Fri Jul 29 20:51:21 UTC 2011 i686 i686 i386 GNU/Linux

the Getting Started tutorial says that I can put melt folder on a subdirectory ... I'll try this night with 64 bit version

**Comment by antonellomangone** [comment]
I can also add that the framework doesn't recognize the web server ... in 32 and 64 bits ..

**Comment by hnsl** [comment]
Try changing the RewriteBase to /melt/ in .htaccess.

Also not recognizing the web server is not dangerous, it simply means that you're more "on your own". Just click pass the warning to ignore it. :)

**Comment by antonellomangone** [comment]
The suggest you gave me doesn't work ... 
I downloaded the zip file in the /var/www folder 
I unzipped it and I renamed the folder melt-melt-1.3-0-9779055 to melt
then I gived the command chmod 777 -R melt 
I've modified in the .htaccess file RewriteBase to /melt/

and when I try to start the console from the browser It gives me the following error:

Not Found

The requested URL /melt/core/console was not found on this server.
Apache/2.2.17 (Ubuntu) Server at localhost Port 80

**Comment by hnsl** [comment]
This might be a stupid question but have you run the bootstrap script first? (/index.php) It automatically generates the .htaccess file and prepares melt rewriting.

**Comment by antonellomangone** [comment]
Yes I did ... :-(

**Comment by antonellomangone** [comment]
I found that http://localhost/melt/core/console doesn't exists 
error 404 Not Found 
....
probably is a problem of routing

**Comment by antonellomangone** [comment]
OK, it's a problem of routing ... doing a virtual host it works great, using as sub-folder it doesn't work ... 
also modifing in .htaccess RewriteBase in these ways:

/melt
/melt/
./melt
./melt/

I tried all, but i think that the problem is in the dispatcher of the framework

**Comment by hnsl** [comment]
Hmm.. interesting. Are you getting an apache 404 or a melt 404?

**Comment by antonellomangone** [comment]
I've never seen a Melt 404 error, but I think it's an Apache 404 error:

Not Found

The requested URL /melt was not found on this server.
Apache/2.2.17 (Ubuntu) Server at localhost Port 80

**Comment by hnsl** [comment]
Then rewriting doesn't work. Maybe your apache configuration ignores .htaccess files. Check the AllowOverride directive.  Also enter some gibberish into the .htaccess file and see if this crashes the server with 50x (it should).

**Comment by antonellomangone** [comment]
I think that It's not AlloOverride because when I did the VirtualHost I didn't used the AllowOverride directive, while for the localhost I tried to use AllowOverride All directive and I didn't worked 

[Wed Sep 28 07:54:25 2011] [error] [client 127.0.0.1] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
[Wed Sep 28 07:54:25 2011] [error] [client 127.0.0.1] Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.

I suggest you to test it under linux

**Comment by antonellomangone** [comment]
***\* SOLVED ***\*  I FOUND THE SOLUTION ... 
When you want to install Melt Framework in a subfolder of the localhost you have to define:

```
<Directory /var/www/melt/>
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Order allow,deny
    allow from all
</Directory>
```

In the  file /etc/apache2/sites-available/default or for other OS in httpd.conf or apache2.conf 

Now it works !!!

**Comment by hnsl** [comment]
I'm glad to hear that you got it working. I hope this solution helps any other people that runs into this issue. The apache-melt integration can be a bit tricky due to different environments and configuration.

**Comment by regularmistake** [comment]
I'm kinda having the same issue.
Running apache2 under Windows 2003.

This is the 'global' directory config in httpd.conf:

```
<Directory "D:\HTDOCS">
    Options Indexes FollowSymLinks
    AllowOverride None
    Order allow,deny
    Allow from all

    AuthName "Test"
    AuthType SSPI
    SSPIDomain domain.com
    SSPIAuth On
    SSPIUsernameCase upper
    SSPIPerRequestAuth Off
    require valid-user   
</Directory>
```

I added antonellomangone's "fix"

```
<Directory "D:\HTDOCS\test\melter">
    Options Indexes FollowSymLinks MultiViews
    AllowOverride All
    Order allow,deny
    allow from all
</Directory>
```

It get's me to the console, but when I enter the password I get '401 Authorization Required'.
GET melter/core/console/check_login 401 Authorization Required

```
Authorization Required

This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required.

Additionally, a 401 Authorization Required error was encountered while trying to use an ErrorDocument to handle the request.
```

Do you know how to fix this?

**Comment by antonellomangone** [comment]
try to check the .htaccess file of the application, probsably you have altered it ...

**Comment by regularmistake** [comment]
It's straight of the box, I didn't touch it, looks like this:

```
# Only utf-8 policy.
AddDefaultCharset utf-8

# Turn off indexing and directory slash correction.
Options -Indexes
DirectorySlash Off

# Enable symlinks.
Options +FollowSymLinks

# Start the rewrite engine.
RewriteEngine On

# Use melt to display error documents.
ErrorDocument 400 /core/core.php
ErrorDocument 401 /core/core.php
ErrorDocument 402 /core/core.php
ErrorDocument 403 /core/core.php
ErrorDocument 404 /core/core.php
ErrorDocument 405 /core/core.php
ErrorDocument 406 /core/core.php
ErrorDocument 407 /core/core.php
ErrorDocument 408 /core/core.php
ErrorDocument 409 /core/core.php
ErrorDocument 410 /core/core.php
ErrorDocument 411 /core/core.php
ErrorDocument 412 /core/core.php
ErrorDocument 413 /core/core.php
ErrorDocument 414 /core/core.php
ErrorDocument 415 /core/core.php
ErrorDocument 416 /core/core.php
ErrorDocument 417 /core/core.php
ErrorDocument 500 /core/core.php
ErrorDocument 501 /core/core.php
ErrorDocument 502 /core/core.php
ErrorDocument 503 /core/core.php
ErrorDocument 504 /core/core.php
ErrorDocument 505 /core/core.php

# Set this to the directory this application is installed in.
RewriteBase /melter

# Rewrite static module files to their appropriate locations.
RewriteRule ^static/cmod/([^/]+)/(.*)$ core/$1/static/$2 [L]
RewriteRule ^static/mod/([^/]+)/(.*)$ modules/$1/static/$2 [L]

# Rewrite everything non-static to melt core.
RewriteCond %{REQUEST_URI} !/static
RewriteRule .* core/core.php [L]
```

**Comment by hnsl** [comment]
It's definitely an apache issue and not a melt issue. Most likely related to the "SSPIAuth On" setting you have there.

Try setting it to off and see if it works.
