### ISSUE TITLE
Bootstrapping script says I am on Windows system even though I am on OSX

### ISSUE THREAD

**Issue by melt** [melt/melt#2]
The bootstrapping script claims that I am running on a Windows-based system even though I am on OSX.

**Comment by hnsl** [comment]
Could you please run die(var_dump(PHP_OS)) and see what it outputs on your system.

**Comment by perjonsson** [comment]
It outputs string(6) "Darwin".

I am on OSX 10.6.7 using PHP 5.3.6 via the Macports installer.

**Comment by hnsl** [comment]
What an amazing coincidence. "Darwin" contains "win" which is the string it tries to find to check if the OS is Windows.
