### ISSUE TITLE
Cannot edit model when using new AircraftModel($id);

### ISSUE THREAD

**Issue by kerma** [melt/melt#20]
From Solutions wiki page:

```
<?php namespace melt;
class AdminController extends AppController {
    public function edit_aircraft($id) {
        $this->aircraft = new AircraftModel($id);
        if ($this->aircraft === null)
            $this->aircraft = new AircraftModel();
    }
}
```

This actually does not work. New instance is created with correct data, but isLinked() returns false and getID() returns 0, instead of $id.

Therefore the following code in your view:

```
<?php namespace melt; ?>
<?php $interface = new qmi\ModelInterface("edit_aircraft"); ?>
<?php echo $interface->startForm(); ?>
    <?php echo $interface->getInterface($this->aircraft); ?>
<?php echo $interface->finalizeForm(true, true); ?>
```

...does not work correctly and you see a form for adding new model. However adding a new model through this form does not work either, data is not saved.

Workaround is to use the following in your controller:

```
<?php namespace melt;
class AdminController extends AppController {
    public function edit_aircraft($id = null) {
        if ($id === null)
            $this->aircraft = new AircraftModel();
       else
           $this->aircraft = AircraftModel->selectByID($id);
    }
}
```

**Comment by hnsl** [comment]
Thanks a lot. Fixed this in the documentation. I must have been a bit tired when I wrote that example.
