### ISSUE TITLE
qmi\ModelInterface finalizeForm() should support custom submit button value

### ISSUE THREAD

**Issue by kerma** [melt/melt#23]
Current finalizeForm() implementation does not support overriding default "Add new" and "Save changes" submit button values. There should be a possibility to add a custom button value when calling finalizeForm(). In most cases "Add new" and "Save changes" are perfectly fine, but in user signup for example I'd rather user something like "Sign up".

**Comment by daniel-marklund** [comment]
Actually it does,

When looking at the definition of the function you will see that it finalizes the interface data and closes the form-tag.
You may also choose if it should echo a submit button and a delete button, finalizeForm($auto_submit = true, $auto_delete = false).

Therefore in your case, you may use the following:

```
<?php $interface = new qmi\ModelInterface...
...
<input type="submit" name="submit" value="Sign up" />
<?php echo $interface->finalizeForm(false); ?>
```

**Comment by kerma** [comment]
Thanks, I didn't think about it like that for some reason :)
