### ISSUE TITLE
build command

### ISSUE THREAD

**Issue by antonellomangone** [melt/melt#5]
The build command on the web console doesn't exist (I found it in the documentation), but I understand that probably the basic application is created at the beginning, so I think that the documentation should be corrected.

Best Regards 
Antonello Mangone

**Comment by melt** [comment]
Hey Antonello!

Please wait for the 1.0.0 milestone to be completed. It is scheduled for Monday.

The milestone will include a sample application with useful code snippets that you will be able to generate using the _build_ command.

**Comment by perjonsson** [comment]
Antonello,

Issue should now be resolved. Check the documentation for updated commands: 
https://github.com/melt/melt/wiki/Getting-Started-with-Melt.

Also make sure to grab the latest version (1.0) since we have updated a few things from the development release.

**Comment by antonellomangone** [comment]
Thank you very much, I'll test it soon
Antonello

2011/8/1 per-jonsson <
reply@reply.github.com>
